"""
Root Cause Assessor

Evaluates investigation hypotheses against collected evidence
and determines the most likely root cause.

This component is deterministic for now.

Later it can be enhanced with:
- LLM-assisted reasoning
- RAG/runbook evidence
- historical incidents
- confidence scoring
"""

from typing import Any, Dict, List, Optional


class RootCauseAssessor:
    """
    Determines the most likely root cause from hypotheses
    and collected investigation evidence.
    """

    # ============================================================
    # Evidence scoring
    # ============================================================

    SUPPORTING_EVIDENCE_SCORE = 2

    CONTRADICTING_EVIDENCE_SCORE = -2

    RELATED_EVIDENCE_SCORE = 1

    # ============================================================
    # Public API
    # ============================================================

    def assess(
        self,
        hypotheses: List[Dict[str, Any]],
        evidence: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """
        Assess all hypotheses against collected evidence.

        Args:
            hypotheses:
                Hypotheses generated by the HypothesisEngine.

            evidence:
                Evidence collected during investigation.

        Returns:
            Structured root-cause assessment.
        """

        if not hypotheses:

            return {
                "root_cause": None,
                "score": 0,
                "supporting_evidence": [],
                "contradicting_evidence": [],
                "assessment": "No hypotheses available.",
            }

        assessments = []

        for hypothesis in hypotheses:

            assessment = (
                self._assess_hypothesis(
                    hypothesis,
                    evidence,
                )
            )

            assessments.append(
                assessment
            )

        assessments.sort(
            key=lambda item: item["score"],
            reverse=True,
        )

        best = assessments[0]

        return {
            "root_cause": best["hypothesis"],
            "score": best["score"],
            "supporting_evidence": (
                best["supporting_evidence"]
            ),
            "contradicting_evidence": (
                best["contradicting_evidence"]
            ),
            "assessment": self._build_assessment(
                best
            ),
            "all_assessments": assessments,
        }

    # ============================================================
    # Hypothesis Assessment
    # ============================================================

    def _assess_hypothesis(
        self,
        hypothesis: Dict[str, Any],
        evidence: List[Dict[str, Any]],
    ) -> Dict[str, Any]:
        """
        Score one hypothesis against evidence.
        """

        hypothesis_text = str(
            hypothesis.get(
                "hypothesis",
                ""
            )
        )

        hypothesis_lower = (
            hypothesis_text.lower()
        )

        score = 0

        supporting = []

        contradicting = []

        related = []

        for evidence_item in evidence:

            result = evidence_item.get(
                "result"
            )

            if not isinstance(
                result,
                dict,
            ):
                continue

            evidence_text = (
                self._evidence_to_text(
                    evidence_item
                )
            )

            evidence_lower = (
                evidence_text.lower()
            )

            evidence_type = (
                self._classify_evidence(
                    hypothesis_lower,
                    evidence_lower,
                )
            )

            if evidence_type == "supporting":

                score += (
                    self.SUPPORTING_EVIDENCE_SCORE
                )

                supporting.append(
                    evidence_item
                )

            elif evidence_type == "contradicting":

                score += (
                    self.CONTRADICTING_EVIDENCE_SCORE
                )

                contradicting.append(
                    evidence_item
                )

            elif evidence_type == "related":

                score += (
                    self.RELATED_EVIDENCE_SCORE
                )

                related.append(
                    evidence_item
                )

        return {
            "hypothesis": hypothesis_text,
            "score": score,
            "supporting_evidence": supporting,
            "contradicting_evidence": contradicting,
            "related_evidence": related,
        }

    # ============================================================
    # Evidence Classification
    # ============================================================

    def _classify_evidence(
        self,
        hypothesis: str,
        evidence: str,
    ) -> Optional[str]:
        """
        Determine whether evidence supports,
        contradicts, or is related to a hypothesis.

        The rules are intentionally conservative.
        """

        # --------------------------------------------------------
        # Resource saturation
        # --------------------------------------------------------

        if (
            "resource saturation"
            in hypothesis
            or "high cpu"
            in hypothesis
            or "high memory"
            in hypothesis
        ):

            if (
                "cpu_utilization"
                in evidence
                or "memory_utilization"
                in evidence
                or "high cpu"
                in evidence
                or "high memory"
                in evidence
            ):
                return "supporting"

            if (
                "normal cpu"
                in evidence
                or "normal memory"
                in evidence
            ):
                return "contradicting"

        # --------------------------------------------------------
        # Degraded instance
        # --------------------------------------------------------

        if (
            "degraded instance"
            in hypothesis
            or "instance health"
            in hypothesis
        ):

            if (
                "health"
                in evidence
                and (
                    "degraded"
                    in evidence
                    or "unhealthy"
                    in evidence
                )
            ):
                return "supporting"

            if (
                "health"
                in evidence
                and "healthy"
                in evidence
            ):
                return "contradicting"

        # --------------------------------------------------------
        # Network
        # --------------------------------------------------------

        if (
            "network"
            in hypothesis
        ):

            if (
                "network_status"
                in evidence
                and (
                    "unhealthy"
                    in evidence
                    or "failed"
                    in evidence
                    or "unavailable"
                    in evidence
                    or "degraded"
                    in evidence
                )
            ):
                return "supporting"

            if (
                "network_status"
                in evidence
                and (
                    "normal"
                    in evidence
                    or "healthy"
                    in evidence
                    or "available"
                    in evidence
                )
            ):
                return "contradicting"

        # --------------------------------------------------------
        # Application errors
        # --------------------------------------------------------

        if (
            "application"
            in hypothesis
            or "application error"
            in hypothesis
        ):

            if (
                "error"
                in evidence
                or "http 500"
                in evidence
                or "timeout"
                in evidence
                or "exception"
                in evidence
            ):
                return "supporting"

            if (
                "no errors"
                in evidence
                or "healthy application"
                in evidence
            ):
                return "contradicting"

        # --------------------------------------------------------
        # Deployment
        # --------------------------------------------------------

        if (
            "deployment"
            in hypothesis
            or "release"
            in hypothesis
        ):

            if (
                "deployment"
                in evidence
                and (
                    "failed"
                    in evidence
                    or "failure"
                    in evidence
                )
            ):
                return "supporting"

            if (
                "deployment"
                in evidence
                and (
                    "success"
                    in evidence
                    or "successful"
                    in evidence
                )
            ):
                return "contradicting"

        # --------------------------------------------------------
        # Generic relationship
        # --------------------------------------------------------

        hypothesis_words = {
            word
            for word in hypothesis.split()
            if len(word) > 4
        }

        evidence_words = {
            word
            for word in evidence.split()
            if len(word) > 4
        }

        if hypothesis_words.intersection(
            evidence_words
        ):

            return "related"

        return None

    # ============================================================
    # Evidence Formatting
    # ============================================================

    def _evidence_to_text(
        self,
        evidence_item: Dict[str, Any],
    ) -> str:
        """
        Convert evidence into searchable text.
        """

        parts = []

        tool = evidence_item.get(
            "tool"
        )

        if tool:
            parts.append(
                str(tool)
            )

        arguments = evidence_item.get(
            "arguments"
        )

        if arguments:
            parts.append(
                str(arguments)
            )

        result = evidence_item.get(
            "result"
        )

        if result:
            parts.append(
                str(result)
            )

        return " ".join(
            parts
        )

    # ============================================================
    # Assessment Summary
    # ============================================================

    def _build_assessment(
        self,
        assessment: Dict[str, Any],
    ) -> str:
        """
        Build a human-readable root-cause assessment.
        """

        hypothesis = assessment[
            "hypothesis"
        ]

        score = assessment[
            "score"
        ]

        supporting_count = len(
            assessment[
                "supporting_evidence"
            ]
        )

        contradicting_count = len(
            assessment[
                "contradicting_evidence"
            ]
        )

        if score > 0:

            return (
                f"Most likely root cause: "
                f"{hypothesis}. "
                f"The hypothesis has "
                f"{supporting_count} supporting "
                f"evidence item(s) and "
                f"{contradicting_count} "
                f"contradicting evidence item(s)."
            )

        if score == 0:

            return (
                f"Root cause remains uncertain. "
                f"The strongest hypothesis is: "
                f"{hypothesis}, but available "
                f"evidence is insufficient "
                f"to confirm it."
            )

        return (
            f"Root cause remains uncertain. "
            f"The hypothesis '{hypothesis}' "
            f"has more contradicting evidence "
            f"than supporting evidence."
        )